### ISSUE TITLE
Issues with latest Oscar64

### ISSUE THREAD

**Issue by shinaka** [MihaMarkic/modern-vice-pdb-monitor#1]
I’ve been hoping to use this as I develop a game I’ve been buiding on top of Oscar64 - unfortunately the current version has a few issues. Locally I added support for the enum type, which got me past the first hurdle, then a crash on a duplicate variable name from the indexer of an unrolled loop when creating the dictionary. Fixing those up got me something that sort of works, except the local variables at a break point are all wrong and repeating, usually infinitely nested.

I hope things are still in development, as a tool like this is incredibly exciting for ‘new’ retro development!

**Comment by MihaMarkic** [comment]
Hey, thanks for warm words. I haven't update to latest Oscar64 for a while and I suppose that's why you are seeing the issues.
Can you provide a simple repro and exact oscar64 version you are using. I'll take a look.

**Comment by shinaka** [comment]
Hey - sorry for the delayed reply; been dealing with a family emergency. I can put together a small repro, or, I have the game I'm currently working on set to public on Github @ https://github.com/shinaka/c64-oscar-test which should display the various issues. I'm currently on the latest Oscar64 (as of 11/12) - I build it locally.

Thanks for any help you can provide - your tool would honestly be a HUGE time saver for me!

**Comment by MihaMarkic** [comment]
@shinaka Hey, can't compile your sources with latest Oscar64, gettings this:
```
"C:\Program Files (x86)\oscar64\bin\oscar64.exe" .\main.cpp -g -tm=c64 -tf=prg -n -O0
D:/Temp/oscar64/c64-oscar-test/src/ui/hud.cpp(14, 74) : error 3043: No matching function call 'BottomHUDWindow::+BottomHUDWindow'
D:/Temp/oscar64/c64-oscar-test/src/ui/hud.cpp(15, 74) : error 3043: No matching function call 'PlayerInfoPane::+PlayerInfoPane'
D:/Temp/oscar64/c64-oscar-test/src/ui/hud.cpp(16, 57) : error 3043: No matching function call 'SkillBar::+SkillBar'
D:/Temp/oscar64/c64-oscar-test/src/ui/hud.cpp(69, 74) : error 3043: No matching function call 'Window::+Window'
```

**Comment by shinaka** [comment]
You’ll need to compile Oscar - he’s made some fixes as I’ve hit issues.

**Comment by MihaMarkic** [comment]
It crashes when compiled from latest sources though

**Comment by shinaka** [comment]
You're right, if it's compiled with -O0, Oscar seems to crash. I've pinged DrMortalWombat to help track the issue down

**Comment by shinaka** [comment]
He's still looking into the crash, but I've submitted a change to my repo that should let you build now.

**Comment by MihaMarkic** [comment]
Do you mind trying with latest Oscar64 sources and my develop branch?

**Comment by MihaMarkic** [comment]
Will close it since lack of feedback. Feel free if there is any reason to reopen.
