### ISSUE TITLE
MVPM consistently shows errors when reading oscar64-generated .dbj files

### ISSUE THREAD

**Issue by coslor** [MihaMarkic/modern-vice-pdb-monitor#3]
When I create or update an MPVM project using a newly-oscar64-generated .dbj file, I consistently get errors like :
`Failed parsing, Text = Failed assigning source line to address 9697 because of duplicate`. 
As soon as the Monitor sees the duplicate, it stops dead. 

When I look at the .dbj file, I see entries like:
```
			{"start": 9697, "end": 9697, "source": "C:/Users/chris/oscar64/include/c64/keyboard.c", "line": 100},
			{"start": 9697, "end": 9704, "source": "C:/Users/chris/oscar64/include/c64/keyboard.c", "line": 99},
```
If I go into the .dbj and remove one of the duplicate lines, MVPM gets further...until the next duplicate set. I typically have to do this 3 or 4 times every time I build, which makes it a real pain to use as part of a build...debug...build cycle. 

I don't know if the duplicate entries are a bug in oscar64, or a result of my faulty memory configuration, or what, but could you make MVPM more tolerant of such errors? One way of doing that would be to simply make the "duplicate" error nonfatal, but hey, you're the boss! As long as I can get past the errors I would be happy.

P.S. I *love* having a source-level C debugger for C development on the 6502 platforms! it makes life so much easier. You have the beginnings of something truly great here.

**Comment by MihaMarkic** [comment]
@coslor Yes, it can be either MVPM or Oscar64. Can you attach your sources and generated dbj file so I can repro?

**Comment by coslor** [comment]
I'm attaching a test project to replicate the issue. As I said, it's possible that I'm just configuring my sections improperly or something.
[mvpm_bug.zip](https://github.com/MihaMarkic/modern-vice-pdb-monitor/files/14348074/mvpm_bug.zip)

**Comment by MihaMarkic** [comment]
@coslor It was a bug in Oscar64, try with building it with latest sources and compilation should produce correct debug symbols.

**Comment by MihaMarkic** [comment]
Will close it since lack of feedback. Feel free if there is any reason to reopen.
