### ISSUE TITLE
SDL VICE places executable in its base directory, not in a bin subdirectory.

### ISSUE THREAD

**Issue by MarcusLlewellyn** [MihaMarkic/modern-vice-pdb-monitor#4]
At the moment, a `bin` string is automatically appended to the base path for VICE. This matches what is expected from the GTK version, but the SDL version does not have this. Rather, it places all of the executables in the base directory.

If a suggestion is welcome, an easy fix might be to add a GUI element to select which version of VICE is being used and skip appending `bin` for SDL.

**Comment by MihaMarkic** [comment]
Hey, suggestions are always welcome. Didn't know of that discrepancy, thanks for letting me know. I think I'll try to make it automatic - check if bin directory exists and if not, look in the root directory.

**Comment by MihaMarkic** [comment]
@MarcusLlewellyn I've implemented it, it should now automatically detect between root and bin sub directory. However, when I tested with SDL version it crashes for some reason when I try to start debugging. Can you give it a try (build from sources)?
